apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'example@gmail.com'
      smtp_auth_username: 'example@gmail.com'
      smtp_auth_password: 'supersecretpassword'
    route:
      group_by: ['alertname']
      receiver: 'email-alert'
    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'example@gmail.com'
            send_resolved: true
